import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import { Toaster } from 'react-hot-toast'

// font changer

const inter = Inter({ subsets: ['latin'] })

//----

// <head> tag in HTML
export const metadata: Metadata = {
  title: 'Roamradar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <RegisterModal/>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
